---
- name: Configure cloud-init
  file:
    dest: /srv/http/cloud-init
    state: directory

- name: Configure meta-data
  template:
    src: meta-data.j2
    dest: /srv/http/cloud-init/meta-data
#    dest: /srv/tftp/meta-data

- name: Configure user-data
  template:
    src: user-data.j2
    dest: /srv/http/cloud-init/user-data
#    dest: /srv/tftp/user-data

