---
- name: Create directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/srv/http"
    - "/srv/tftp"
    - "/srv/tftp/pxelinux.cfg"

- name: Configure dnsmasq
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/pxe.conf
  register: dnsmasq

- name: Configure http server
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/pxe.conf
  register: nginx

- name: Configure http server
  template:
    src: pxelinux.cfg.j2
    dest: /srv/tftp/pxelinux.cfg/default
  register: nginx

- name: Disable default site
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent

- name: Enable site
  file:
    src: /etc/nginx/sites-available/pxe.conf
    dest: /etc/nginx/sites-enabled/pxe.conf
    state: link

#- name: Copy a BIOS boot files 
#  copy:
#    src: "/usr/lib/syslinux/modules/bios/{{ item }}"
#    dest: /srv/tftp/
#    remote_src: yes
#  with_items:
#    - "ldlinux.c32"
#    - "vesamenu.c32"

- name: Copy BIOS Boot files
  shell:
    cmd: cp /usr/lib/syslinux/modules/bios/*.c32 /srv/tftp/

- name: Restart TFTP server
  service:
    name: dnsmasq
    enabled: yes
    state: restarted
  when: dnsmasq.changed

- name: Restart nginx server
  service:
    name: nginx
    enabled: yes
    state: restarted


